[package]
name = "engulf-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "engulf"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
engulf = { path = "../engulf" }
