[package]
name = "engulf-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0"
engulf = { path = "../engulf" }
wasm-bindgen = "0.2"
getrandom = { version = "0.3", features = ["wasm_js"] }
